language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: LOhvVU2O9yUiUgzl91BOLDkrfva50FWYIWhmo2OR44i4z1HEUi2tf6CWFj7SA3jzX7DvYGwe3fwMXIqosh5erf9ycQGZqhi+DqtijdH54j2G65Snum6s8fa2RB/Z3GN0LcDiltW7C3p6bNzqBkDuAuug6/KRA3K35x42elsflFFAelOFWJ97uL4qDv/jGfu4vh6kAt1XQJ72U6enk6F1DONZ1dYlkLUgCQ9t7u7QKJEJZzbZxMuqxkbVHbfbLCljBlNY9FRoEfu7u+fe2egjAZscITAqdfB1aYIYDz9TvVrc70DFjP95/klPn0Eio5MERFDz5XSt92//zh6m/uBRXb4jqAYp8m0eZa7wsKlPN25dmlmDSIUx4dyco9T1L8xd8mcE2xEBtJNOMNYJktarW0LGU35xioojimu1n0ht3xYuVvJJK+LmU73Rbngiw/5YtMpziMOB2kIcNMDHdDPx/ctLGSn1XrXN2234ryDiakUqfT3xaQ+S6ZnMDHXUR99AbAGxuJqV0hh2iDsjSpyYjwv4gldtU3FAntDDFC2bCJb6XFSem8LftECIMhGJJaVlhayjecxsi/0p1F89C7HM0Cs0LTDlSoaJuMsKDYQ7Qd6RV1gmd2AQQti+JSuuodKvLuzEqnvDa/MkaVVrbj3hkf8OAsiJE00uOGKpFa11vek=
  app: enigmatic-sands-99732
  on:
    repo: jwoleslagle/blog-app-testing
